"""
Django settings for undergym project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'j4t8b-htj3%e0vi!eazyysx%tch$w3#u=*@c$3njqc9&!j!x9r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1','localhost','undergym.com.br','ag-br1-5.hospedagemelastica.com.br','yjtskb.hospedagemelastica.com.br','177.131.140.155']


SESSION_EXPIRE_AT_BROWSER_CLOSE = True # se fechar o navegador encerra a sessão (isso inclui desligamento do sistema, reiniciar, etc...)
SESSION_COOKIE_AGE = 3600   # 1 hora para expirar a sessão (se nao fizer nada no sistema)
SESSION_SAVE_EVERY_REQUEST = True # renova a sessão a cada requisição



# Application definition

INSTALLED_APPS = [
    'mainapp',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'global_permissions',
    'auditlog',
    'widget_tweaks',
    'easy_mask',
    'django.contrib.humanize',
    'cpf_field',
    'rest_framework',
    'mail_templated'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'auditlog.middleware.AuditlogMiddleware',

]

ROOT_URLCONF = 'undergym.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages'

            ],
        },
    },
]

WSGI_APPLICATION = 'undergym.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'yjtskb_bdpsq',
        'USER': 'yjtskb_user',
        'PASSWORD': ')328hFJhj',
        'HOST': 'postgres-ag-br1-1.hospedagemelastica.com.br',   # Or an IP Address that your DB is hosted on
        'PORT': '',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

TIME_ZONE = 'UTC'
LANGUAGE_CODE = 'en-us'
USE_I18N = True

USE_L10N = True

USE_TZ = True


# E-MAIL RECUPERAÇÃO DE SENHA

EMAIL_HOST = 'smtp.zoho.com'
EMAIL_HOST_USER = 'nao-responda@undergym.com.br'
EMAIL_HOST_PASSWORD = 'selecT&%#'
EMAIL_PORT = 587
EMAIL_USE_TLS = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
#STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'



LOGIN_REDIRECT_URL = '/index/'
LOGOUT_REDIRECT_URL = '/accounts/login'

MEDIA_URL = "/img/"

STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'static')
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'static/mainapp/img')
