# Generated by Django 3.1.2 on 2021-02-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NivelCurso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('curso', models.IntegerField(choices=[(0, 'Inglês'), (1, 'Espanhol'), (2, 'Psicologia'), (3, 'Informática'), (4, 'Matemática')], default=0)),
                ('nivel', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=100)),
                ('ordem', models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], default=0)),
                ('livro', models.ImageField(blank=True, null=True, upload_to='')),
                ('editora', models.DateField()),
                ('edicao', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=100)),
                ('ativo', models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], default=0)),
                ('gera_certificado', models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], default=0)),
                ('carga_horaria', models.CharField(max_length=100)),
                ('iniciante', models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], default=0)),
                ('idade_inicial', models.CharField(max_length=100)),
                ('idade_final', models.CharField(max_length=100)),
                ('falta_reprova', models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], default=0)),
                ('nota_reprova', models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], default=0)),
                ('modalidade', models.IntegerField(choices=[(0, 'Presencial'), (1, 'Ead')], default=0)),
                ('font_color', models.CharField(max_length=100)),
                ('backgroud', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'nivel_curso',
                'ordering': ['curso'],
            },
        ),
    ]
