# Generated by Django 3.1.2 on 2021-03-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivelcurso',
            name='livro',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nivelcurso',
            name='nivel',
            field=models.IntegerField(choices=[(0, 'STARTER'), (1, '1A'), (2, '1B'), (3, '2A'), (4, '2B')], default=0),
        ),
        migrations.AlterField(
            model_name='nivelcurso',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
    ]
