# Generated by Django 3.1.2 on 2021-03-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210301_0312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nivelcurso',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='nivelcurso',
            name='editora',
            field=models.CharField(max_length=100),
        ),
    ]
